### ISSUE TITLE
Feature request: ability to process Toasts even when tree is paused

### ISSUE THREAD

**Issue by davcri** [godot-journey-adventures/toastparty#3]
First of all thanks for toastparty, setting it up in Godot 4 was pretty easy!

**Request:** could it be possible to add an exported variable to control the tweens process mode? 

**Why:** toasts stop working when pausing the tree (because of how tweens are processed). Sometimes though users want to pause the game and have the toasts keep working. In such cases tweens should be created with a code like:
```gd
_tween_in = get_tree().create_tween()
if user_want_toasts_during_paused_tree:
   _tween_in.set_pause_mode(Tween.TWEEN_PAUSE_PROCESS) 
```
See https://docs.godotengine.org/en/stable/classes/class_tween.html#enum-tween-tweenpausemode

**Comment by gammafp** [comment]
It is a good idea, I set Tween.TWEEN_PAUSE_PROCESS for all toats!
